instance:
  instanceId: "MARKETPLACE"
  app: 'MARKETPLACE'
  hostName: 'localhost'
  ipAddr: '127.0.0.1'
  statusPageUrl: 'http://localhost:4200'
  port:
   '$': 4200,
   '@enabled': 'true'
  vipAddress: 'MARKETPLACE'
  dataCenterInfo:
    '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo'
    name: 'MyOwn'
eureka:
  host: 'admin:admin@localhost'
  port: 8761
  servicePath: '/eureka/apps/'